/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ActionLogListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheActionLogListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheActionLogListGenerated.onFilterBar().iCheckFilterField({ property: "userEmailId" });
            Then.onTheActionLogListGenerated.onFilterBar().iCheckFilterField({ property: "tcType" });
            Then.onTheActionLogListGenerated.onFilterBar().iCheckFilterField({ property: "tcSubType" });
            Then.onTheActionLogListGenerated.onFilterBar().iCheckFilterField({ property: "versionNumber" });
            Then.onTheActionLogListGenerated.onFilterBar().iCheckFilterField({ property: "status" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheActionLogListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheActionLogListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheActionLogListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheActionLogListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"userEmailId":{"header":"Email ID"},"firstName":{"header":"First Name"},"lastName":{"header":"Last Name"},"tcTypeSubType":{"header":"T&C Type / Sub Type"},"versionNumber":{"header":"Version"},"status":{"header":"Status"},"acceptedOn":{"header":"Accepted / Declined On"},"lastLoginDate":{"header":"Last Login Date"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheActionLogListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheActionLogListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheActionLogListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheActionLogObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});